### ISSUE TITLE
can navigate from home to choice_quiz or written_quiz

### ISSUE THREAD

**Issue by Meri11Ra1** [yambaru-hackathon/ex3_flutter_quiz_app#1]
# todo

- [x] add two screen file, choice_quiz.dart and written_quiz 
- [x] initialize both screen
- [x] can navigate both screen
- [x] can navigate in mode change format
